### ISSUE TITLE
Graph on home page broken

### ISSUE THREAD

**Issue by TiberiusB** [Sensorica/VerdunNRP#13]
The graph on the first page, links are broken. 
http://verdun.valnet.webfactional.com/

See the Sensorica NRP for comparison. 
http://nrp.sensorica.co/ 

Thanks @Tim for finding it.

**Comment by sqykly** [comment]
The HomePageLayout in the DB had the dimensions of the image manually set wrong.  Fixed with the real dimensions, checked it out, works.
