### ISSUE TITLE
accounting/resource/ can't display units of quantity or use

### ISSUE THREAD

**Issue by sqykly** [Sensorica/VerdunNRP#19]
Somehow the resource.resource_type is getting cast to string, preventing the template from accessing its properties, namely unit_of_quantity and unit_of_use.

**Comment by sqykly** [comment]
@bhaugen Both EconomicResource and EconomicResourceType have a value_per_unit_of_use; in what circumstances would these both be used/different?  The resource's instance value_per_unit_of_use the actual purchase price or price to manufacture from recipe, whereas the resource type's is hypothetical or estimated?

**Comment by sqykly** [comment]
Fixed

**Comment by bhaugen** [comment]
@sqykly the unit of use is for EventType Use for inputs to processes, which is for time-based resources like equipment or spaces.

Use is not like Consume, which means the consumed quantity of the resource is gone. With Use, the resource is still there, available again after use. 

Reason for different units is that e.g. a 3d printer has a quantity of unit Each when you want to know how many of them you got, but the unit of use might be "Hour".

Does that make sense?

If you want to be more conceptual, there's another way to do this, which we could get into on request, but it's pretty much a forced move to differentiate Used from Consumed resources.

**Comment by bhaugen** [comment]
Value on the resource should override the resource type. Like, this 3d printer is different from that other 3d printer.
