### ISSUE TITLE
AttributeError at /accounting/exchanges/

### ISSUE THREAD

**Issue by sqykly** [Sensorica/VerdunNRP#20]
Navigate Supply > Exchange List

Error reports that 'QuerySet' object has no attribute 'union'

Citing
/home/valnet/webapps/verdunnrp/VerdunNRP/valuenetwork/valueaccounting/views.py in union

return qs1.union(qs2) if qs1 else qs2

Stack trace reveals that qs1 and qs2 are both non-null, non-empty QuerySet objects of the same model.  Django docs (https://docs.djangoproject.com/en/1.11/ref/models/querysets/#union) are clear that QuerySet objects do, indeed, have a union() method.  So this is a real mystery.

**Comment by bhaugen** [comment]
Change them to sets.

**Comment by sqykly** [comment]
@bhaugen that would fix the exception.  Do Django templates care if they get `set`s instead of `QuerySet`s?

**Comment by sqykly** [comment]
Looks like it works.  Thanks @bhaugen!
